services:
  queue:
    # deploy:
    #   resources:
    #     limits:
    #       memory: 50M
    #       cpus: '1'
    container_name: queue
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7500:7500"
    volumes:
      - data:/data

volumes:
  data:
